### ISSUE TITLE
Error when using -overwrite on MG License Report

### ISSUE THREAD

**Issue by jimbanach** [Canthv0/MSOLLicenseManagement#3]
If you use the -overwrite flag on the MG license report, it's throwing an error when creating the file.  Looking at it, it appears that it's doing that because the variable $logfile isn't defined anywhere.

```
Split-Path : Cannot bind argument to parameter 'Path' because it is null.
At \WindowsPowerShell\Modules\MSOLLicenseManagement\3.0.0\Cmdlet\Get-MGUserLicenseReport.ps1:207char:39
+         $path = Join-path (Split-Path $LogFile -Parent) ("License_Rep ...
+                                                         
+ CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCommand
```

from there the rest of the report generation errors out because the $path variable never gets anything added to it. 

looks like $logfile just needs to be defined or pulled from the broader module.

**Comment by Canthv0** [comment]
Thanks for the find.  Issue is a leftover of the conversion from MSOL to Graph and the associated changes.

Should be resolved in 3.0.2 version.
